#!/bin/bash
# scripts/vault-bootstrap.sh
# Source: BLOCKERS.md B22 + docs/build-log.md §2026-05-26 OWED item #20.
#
# One-shot baseline-commit for Russell's vault git repo. Idempotent: skips the
# commit if vault git already has at least one commit.
#
# Writes the vault .gitignore (if absent) + bulk-stages everything + commits.
# Does NOT push (vault has no remote configured by default; Russell decides).
#
# DO NOT EXECUTE THIS SCRIPT automatically. Russell runs it at Ch.2 prep.
# See ADR §8 + DOCTRINE law #10 — orchestrator does not auto-commit Russell's
# working-tree.
#
# Usage:
#   VAULT_PATH="/path/to/vault" ./scripts/vault-bootstrap.sh
#   ./scripts/vault-bootstrap.sh "/path/to/vault"
#   (defaults to Business Planning vault path)

set -uo pipefail

VAULT_PATH="${VAULT_PATH:-${1:-/Users/russellteter/Documents/Claude/Projects/Business Planning}}"

red()    { printf '\033[31m%s\033[0m\n' "$*"; }
green()  { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }

if [ ! -d "$VAULT_PATH" ]; then
  red "Vault path missing: $VAULT_PATH"
  exit 2
fi

if [ ! -d "$VAULT_PATH/.git" ]; then
  yellow "Vault is not git-initialized; initializing..."
  git -C "$VAULT_PATH" init -q
fi

# Idempotency: skip if vault already has a commit.
if git -C "$VAULT_PATH" log --oneline -1 >/dev/null 2>&1; then
  green "Vault already has at least one commit — skipping bootstrap."
  git -C "$VAULT_PATH" log --oneline -1
  exit 0
fi

# Write .gitignore if absent.
GITIGNORE="$VAULT_PATH/.gitignore"
if [ ! -f "$GITIGNORE" ]; then
  cat > "$GITIGNORE" <<'EOF'
# C-Suite vault .gitignore — generated by scripts/vault-bootstrap.sh
.DS_Store
*.tmp-*
*.proposed-*
_extracted_skills_for_c_suite.md
**/.obsidian/workspace.json
**/.obsidian/workspaces.json
EOF
  green "Wrote .gitignore: $GITIGNORE"
fi

# Bulk stage + commit baseline.
git -C "$VAULT_PATH" add .
STAGED=$(git -C "$VAULT_PATH" diff --cached --numstat | wc -l | tr -d ' ')
SIZE=$(git -C "$VAULT_PATH" diff --cached --numstat | awk '{ a += $1; d += $2 } END { print a "+/" d "-" }')

git -C "$VAULT_PATH" commit -q -m "vault: pre-C-Suite SafeWrite baseline"
SHA=$(git -C "$VAULT_PATH" log --oneline -1 --format=%H)

green "Bootstrap commit complete."
echo "  Files staged: $STAGED"
echo "  Size delta:   $SIZE"
echo "  Commit SHA:   $SHA"
echo
yellow "Note: vault has no remote configured. Russell sets origin if off-Mac backup is desired."
