/**
 * ADR-0006 §8 AC-11 — 8 UI mockups generated by Ch.5 Runtime
 * Test owner: Ch.5 Test dispatch (writer ≠ grader, DOCTRINE law #7)
 * Source: docs/decisions/0006-ch5-cash-lever-slice.md §2 (UI screens design gate)
 *         docs/decisions/0006-ch5-cash-lever-slice.md §8 AC-11
 *         docs/architecture/ui.md §design tokens
 *
 * STATUS: RED until Ch.5 Runtime ships (mockups generated by Ch.5 Runtime via html-driven-codev skill).
 *
 * Spec intent (AC-11):
 *   For each of the 8 mockup steps (ADR-0006 §2):
 *   - Verify the HTML file landed at ~/Desktop/cstuite-design-step-{N}.html.
 *   - Skip with explicit message if not yet generated (TDD-red).
 *   - Validate HTML uses design tokens from ui.md:
 *       Navy #0a1849, Gold #c9a14b, Purple #4739e7
 *
 * Mockup steps (ADR-0006 §2 Table):
 *   Step 1: Design-system sheet    → cstuite-design-step-1.html
 *   Step 2: Home (stub)            → cstuite-design-step-2.html
 *   Step 3: Plan-approval          → cstuite-design-step-3.html
 *   Step 4: Round-table — quiet    → cstuite-design-step-4.html
 *   Step 5: Round-table — mid-run  → cstuite-design-step-5.html
 *   Step 6: Round-table — synthesis→ cstuite-design-step-6.html
 *   Step 7: Memo viewer — clean    → cstuite-design-step-7.html
 *   Step 8: Memo viewer — DRAFT    → cstuite-design-step-8.html
 *
 * Design tokens to validate (docs/architecture/ui.md §design tokens):
 *   --color-navy-900: #0a1849
 *   --color-gold-500: #c9a14b
 *   --color-purple-500: #4739e7
 *
 * NOTE: These files land at ~/Desktop/ (os.homedir()/Desktop/) per ADR-0006 §2.
 * Tests skip gracefully (not fail) if file does not exist — this is TDD-red
 * behavior for pre-Runtime state. After Ch.5 Runtime runs, tests go GREEN.
 */

import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

// ── Constants ─────────────────────────────────────────────────────────────────

const DESKTOP = join(homedir(), 'Desktop');

const REQUIRED_DESIGN_TOKENS = [
  { token: '--color-navy-900', hex: '#0a1849',  label: 'Navy primary background' },
  { token: '--color-gold-500', hex: '#c9a14b',  label: 'Gold accent (rigor-clean)' },
  { token: '--color-purple-500', hex: '#4739e7', label: 'Purple accent (agents)' },
];

const MOCKUP_STEPS = [
  { step: 1, name: 'Design-system sheet',    file: 'cstuite-design-step-1.html' },
  { step: 2, name: 'Home stub',              file: 'cstuite-design-step-2.html' },
  { step: 3, name: 'Plan-approval',          file: 'cstuite-design-step-3.html' },
  { step: 4, name: 'Round-table quiet',      file: 'cstuite-design-step-4.html' },
  { step: 5, name: 'Round-table mid-run',    file: 'cstuite-design-step-5.html' },
  { step: 6, name: 'Round-table synthesis',  file: 'cstuite-design-step-6.html' },
  { step: 7, name: 'Memo viewer clean',      file: 'cstuite-design-step-7.html' },
  { step: 8, name: 'Memo viewer DRAFT',      file: 'cstuite-design-step-8.html' },
] as const;

// ── Helper ────────────────────────────────────────────────────────────────────

function readMockupHtml(filename: string): string | null {
  const path = join(DESKTOP, filename);
  if (!existsSync(path)) return null;
  return readFileSync(path, 'utf8');
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe('AC-11 — 8 UI mockups (Ch.5 Runtime RED until Runtime ships)', () => {
  describe('Mockup file existence checks', () => {
    for (const { step, name, file } of MOCKUP_STEPS) {
      it(`Step ${step} (${name}): ${file} — RED if not yet generated`, () => {
        const path = join(DESKTOP, file);
        const exists = existsSync(path);

        if (!exists) {
          // TDD-red: Ch.5 Runtime has not yet generated this mockup.
          // Intentional test failure — goes GREEN when Ch.5 Runtime runs.
          expect(exists, `Mockup step ${step} (${name}) not yet generated by Ch.5 Runtime — file missing: ${path}`).toBe(true);
        } else {
          // GREEN: file exists — proceed to content validation
          expect(exists).toBe(true);
        }
      });
    }
  });

  describe('Design token validation (runs on generated files; skips missing)', () => {
    for (const { step, name, file } of MOCKUP_STEPS) {
      for (const { token, hex, label } of REQUIRED_DESIGN_TOKENS) {
        it(`Step ${step} (${name}) uses ${label} token (${hex})`, () => {
          const html = readMockupHtml(file);

          if (html === null) {
            // File not yet generated — skip without failing
            // (existsCheck test above provides the RED signal)
            return;
          }

          // When file exists, validate it contains the token or its hex value.
          // Design-system sheet (step 1) must define the CSS variable.
          // Other steps must reference it (either the variable name or hex value).
          const hasToken = html.includes(token) || html.includes(hex);
          expect(hasToken,
            `Step ${step} (${name}): missing design token ${token} (${hex}) — check html-driven-codev output`,
          ).toBe(true);
        });
      }
    }
  });

  describe('Design-system sheet specific checks (step 1 — skips if missing)', () => {
    it('Step 1: design-system sheet defines all 3 required CSS custom properties', () => {
      const html = readMockupHtml('cstuite-design-step-1.html');
      if (html === null) {
        // Not yet generated — RED handled by existence check above
        return;
      }
      for (const { token, hex } of REQUIRED_DESIGN_TOKENS) {
        expect(html, `Design-system sheet missing CSS var: ${token}`).toContain(token);
        expect(html, `Design-system sheet missing hex: ${hex}`).toContain(hex);
      }
    });

    it('Step 1: design-system sheet contains :root { ... } block', () => {
      const html = readMockupHtml('cstuite-design-step-1.html');
      if (html === null) return;
      expect(html).toMatch(/:root\s*\{/);
    });
  });

  describe('Memo viewer DRAFT step (step 8 — skips if missing)', () => {
    it('Step 8: DRAFT memo mockup contains amber DRAFT banner marker', () => {
      const html = readMockupHtml('cstuite-design-step-8.html');
      if (html === null) return;
      // Must contain DRAFT text and amber color token
      expect(html.toUpperCase()).toContain('DRAFT');
      const hasAmber = html.includes('#d6883a') || html.includes('rigor-draft') || html.toLowerCase().includes('amber');
      expect(hasAmber, 'DRAFT mockup missing amber color marker').toBe(true);
    });
  });
});
